title: 
  en: Feature List
  fr: Feature List
label: 
  en: Feature List
  fr: Feature List
description:
  en: Idk features
  fr: Idk features
parameters:
    - name: align
      label: Alignment
      description: The content alignment
      type: string
      enum:
          - { label: Center, value: center }
          - { label: Left, value: left }
      default: center
